global:
  scrape_interval: "1s"

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['worker-node1:9100']
        labels:
          group: 'monitoring_node_ex1'
      - targets: ['worker-node2:9100']
        labels:
          group: 'monitoring_node_ex2'
      - targets: ['worker-node3:9100']
        labels:
          group: 'monitoring_node_ex3'
      - targets: ['worker-node4:9100']
        labels:
          group: 'monitoring_node_ex4'
